// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv8ub5OpaGIQ0tjlEDW7IWettVLftX1_0',
    appId: '1:590075049938:web:217e816e8e28c5c8caba0b',
    messagingSenderId: '590075049938',
    projectId: 'chat-app-d5835',
    authDomain: 'chat-app-d5835.firebaseapp.com',
    storageBucket: 'chat-app-d5835.appspot.com',
    measurementId: 'G-G1JM13XS7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdB_l1r149eoY5wcNAsOSd1_PPXvhvtpM',
    appId: '1:590075049938:android:d3aac4923c658ea6caba0b',
    messagingSenderId: '590075049938',
    projectId: 'chat-app-d5835',
    storageBucket: 'chat-app-d5835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUuFaXRmj5Cn_47t7o-8fpa0GdHBL9GNk',
    appId: '1:590075049938:ios:2164a74b018c41fccaba0b',
    messagingSenderId: '590075049938',
    projectId: 'chat-app-d5835',
    storageBucket: 'chat-app-d5835.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUuFaXRmj5Cn_47t7o-8fpa0GdHBL9GNk',
    appId: '1:590075049938:ios:2164a74b018c41fccaba0b',
    messagingSenderId: '590075049938',
    projectId: 'chat-app-d5835',
    storageBucket: 'chat-app-d5835.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv8ub5OpaGIQ0tjlEDW7IWettVLftX1_0',
    appId: '1:590075049938:web:ef28a9bc9faecee9caba0b',
    messagingSenderId: '590075049938',
    projectId: 'chat-app-d5835',
    authDomain: 'chat-app-d5835.firebaseapp.com',
    storageBucket: 'chat-app-d5835.appspot.com',
    measurementId: 'G-QZ8HV4TN8E',
  );
}
